#  Template NodeJS build

#  This template allows you to validate your NodeJS code.
#  The workflow allows running tests and code linting on the default branch.

image: node:16

pipelines:
  branches:
    develop:
      - step:
          name: Build project
          caches:
            - node
          script:
            - npm install --force --legacy-peer-deps
            - ng build --project=core-models && ng build --project=core-services && ng build --project=practice-app --configuration=qa
          artifacts:
            - dist/practice-app
      - step:
          name: Deploy to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-1'
                S3_BUCKET: 'dev.nasbulegal.com'
                LOCAL_PATH: 'dist/practice-app'
                ACL: 'public-read'
    master:
      - step:
          name: Build project
          caches:
            - node
          script:
            - npm install --force --legacy-peer-deps
            - ng build --project=core-models && ng build --project=core-services && ng build --project=practice-app --prod
          artifacts:
            - dist/practice-app
      - step:
          name: Deploy to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-1'
                S3_BUCKET: 'app.nasbulegal.com'
                LOCAL_PATH: 'dist/practice-app'
                ACL: 'public-read'
